/**
 * @fileoverview gRPC-Web generated client stub for server2
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.9
// source: tctxto.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as tctxto_pb from './tctxto_pb'; // proto import: "tctxto.proto"


export class TicTacToeClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSubscribe = new grpcWeb.MethodDescriptor(
    '/server2.TicTacToe/Subscribe',
    grpcWeb.MethodType.SERVER_STREAMING,
    tctxto_pb.SubscribeRequest,
    tctxto_pb.ServerUpdate,
    (request: tctxto_pb.SubscribeRequest) => {
      return request.serializeBinary();
    },
    tctxto_pb.ServerUpdate.deserializeBinary
  );

  subscribe(
    request: tctxto_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<tctxto_pb.ServerUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/server2.TicTacToe/Subscribe',
      request,
      metadata || {},
      this.methodDescriptorSubscribe);
  }

  methodDescriptorNotify = new grpcWeb.MethodDescriptor(
    '/server2.TicTacToe/Notify',
    grpcWeb.MethodType.UNARY,
    tctxto_pb.ClientUpdate,
    tctxto_pb.Empty,
    (request: tctxto_pb.ClientUpdate) => {
      return request.serializeBinary();
    },
    tctxto_pb.Empty.deserializeBinary
  );

  notify(
    request: tctxto_pb.ClientUpdate,
    metadata?: grpcWeb.Metadata | null): Promise<tctxto_pb.Empty>;

  notify(
    request: tctxto_pb.ClientUpdate,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: tctxto_pb.Empty) => void): grpcWeb.ClientReadableStream<tctxto_pb.Empty>;

  notify(
    request: tctxto_pb.ClientUpdate,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: tctxto_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/server2.TicTacToe/Notify',
        request,
        metadata || {},
        this.methodDescriptorNotify,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/server2.TicTacToe/Notify',
    request,
    metadata || {},
    this.methodDescriptorNotify);
  }

}

